# Generated by Django 6.1 on 2026-08-12 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_sha256', models.CharField(help_text='Empreinte SHA-256 qui a été signée (doit correspondre au document).', max_length=64)),
                ('signature_value', models.TextField(help_text='Signature RSA de l’empreinte, encodée en Base64.')),
                ('is_valid', models.BooleanField(default=False, help_text='Résultat de la vérification serveur avec la clé publique.')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_at'],
                'constraints': [models.UniqueConstraint(fields=('document', 'signer'), name='unique_signature_per_document_signer')],
            },
        ),
    ]
